# 오류 객체 잡아내기

앞에서 우리는 함수를 이용하여 오류 타입을 던지는 과정과 이렇게 구현된 함수를 호출하는 방법까지 알아봐써요. 이제 함수를 호출하여 사용하면서 오류가 던져질 경우 이를 잡아내여 적절히 처리하는 것에 대해 알아보죠.

```swift
do {
    try <오류를 던질 수 있는 함수>
} catch <오류 타입1> {
    <오류 처리 구문1>
} catch <오류 타입2>{
    <오류 처리 구문2>
}
```

정상적으로 처리되는 상황을 가정하고 do 구문 내부에 코드를 작성하면 돼요. 컴파일러는 do 구문 내부에 작성된 순서대로 코드를 실행하다가 try 함수 호출에서 오류가 던져지면 이를 catch 구문으로 전달해요. catch 구문은 switch 구문에서의 case처럼 오류 타입 각각을 지정하여 작성할 수 있는데, 이때 각 오류 타입에 대응하는 코드를 작성해야 해요.

```swift
do {
    try parseDate(param: "2020-05-11")
} catch DateParseError.overSizeString {
    print("입력된 문자열이 너무 깁니다.")
} catch DateParseError.underSizeString {
    print("입력된 문자열이 너무 짧습니다.")
} catch DateParseError.incorrectFormat(let part) {
    print("입력된 문자열의 \(part) 부분의 형식이 잘못되었습니다.")
} catch DateParseError.incorrectData(let part) {
    print("입력된 문자열의 \(part) 부분에 입력된 값이 잘못되었습니다.")
} catch {
    print("알 수 없는 오류가 발생하였습니다.")
}
```

이렇게 오류 타입으로 나누어진 catch 구문은 그에 맞는 오류가 던져졌을 때 잡아내게 되고, 그에 맞는 출력 구문을 통해 오류 정보를 보여줘요.

가장 마지막에 오류 타입이 작성되지 않은 catch 구문은 앞의 catch 구문에서 잡히지 않은 모든 오류를 잡아주는 와일드카드 역할을 해요. 위 예제 구문은 단순히 오류 정보를 보여주는 데 그치지만 향후 앱을 제작하는 과정에서는 사용자의 재입력을 유도하던가 잘못된 값을 수정하는 다양한 처리 구문이 들어가야 해요.

오류를 던지도록 설계된 함수나 메소드이지만, 필요에 의해 오류를 던지지 않게 하고 싶을 때는 다음과 같이 try 키워드 대신 try! 키워드를 사용해요.

```swift
let date = try! parseDate(param: "2020-07-07")
```

이 키워드는 강제로 해당 구문을 실행하는 것으로서, 일반적으로 try 키워드를 사용하여 함수를 호출할 경우 오류에 해당하는 경우가 생기면 실행이 멈추고 오류를 던지지만, try! 키워드를 사용하면 오류를 던지지 않고 그대로 함수를 강제 실행하게 돼요.

따라서 이 경우 강제로 함수가 실행되지만, 오류가 발생할 경우 그대로 런타임 오류로 이어져요.

[이전](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/11.12.md)

[처음으로](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/README.md)
