# 오류 던지기

우리가 작성한 오류 타입 객체는 함수나 메소드를 실행하는 과정에서 필요에 따라 외부로 던져 실행 흐름을 옮겨버릴 수 있어요. 이때 함수나 메소드는 오류 객체를 외부로 던질 수 있다는 것을 컴파일러에 알려주기 위해 정의 구문을 작성할 때 throws 키워드를 추가해요.

throws 키워드는 반환 타입을 표시하는 화살표 ('->')보다 앞에 작성해야 하는데, 이는 오류를 던지면 값이 반환되지 않는다는 의미이기도 해요. 명시적으로 throws 키워드를 추가하지 않으면 오류를 던질 수 없어요.

```swift
func canThrowErrors() throws -> String
func cannotThrowErros() -> String
```

클로저를 이용하여 구문을 작성할 때도 이와 비슷하게 반환 화살표 앞에 작성해요.

```swift
{() throws -> String in
    ...
}
```

실제로 날짜를 분석하는 함수를 작성하고, 실행 과정에서 발생할 수 있는 오류 상황에서 오류 객체를 던져볼게요. 앞서 작성한 DateParseError 오류 객체를 사용해요.

```swift
import Foundation

struct Date{
    var year: Int
    var month: Int
    var date: Int
}

func parseDate(param: NSString) throws -> Date {
    guard param.length == 10 else {
        if param.length > 10 {
            throw DateParseError.overSizeString
        } else {
            throw DateParseError.underSizeString
        }
    }

    var dateResult = Date(year: 0, month: 0, date: 0)

    if let year = Int(param.substring(with: NSRange(location: 0, length: 4))) {
        dateResult.year = year
    } else {
        throw DateParseError.incorrectFormat(part: "year")
    }

    if let month = Int(param.substring(with: NSRange(location: 5, length: 2))) {
        guard month > 0 && month < 13 else {
            throw DateParseError.incorrectData(part: "month")
        }
        dateResult.month = month
    } else {
        throw DateParseError.incorrectFormat(part: "month")
    }

    if let date = Int(param.substring(with: NSRange(location: 8, length: 2))) {
        guard month > 0 && month < 32 else {
            throw DateParseError.incorrectData(part: "date")
        }
        dateResult.date = date
    } else {
        throw DateParseError.incorrectFormat(part: "date")
    }

    return dateResult
}
```

위 예제에서 가장 먼저살펴볼 부분은 파운데이션 라이브러리를 호출하는 import Foundation이에요.

우리는 문자열 분석의 편의를 위해 스위프트에서 기본으로 제공하는 String 타입이 아닌 NSString 타입의 문자열을 사용할 예정이에요. 이 타입은 파운데이션 프레임워크에서 제공하는 것으로서 String 타입보다 사용할 수 있는 메소드가 다양해요.

그리고 parseDate(param:) 함수를 보면 throws 키워드가 추가되어 있어요. 이는 함수가 오류를 던질 수 있다는 것을 의미해요. 이제 함수를 호출하는 과정에서 오류가 발생할 수 있다는 것을 컴파일러에 알려줄 수 있어요.

이렇게 정의된 함수나 메소드를 호출할 때는 다음과 같이 호출할 이름 앞에 try 키워드를 붙여야 해요.

> try parseDate(param: "2020-07-07")

이 값을 다른 변수나 상수에 할당할 때도 try 키워드는 항상 함수의 이름 바로 앞에 있어야 하죠.

> let date: Date = try parseDate(param: "2020-07-07")

하지만 try 키워드는 단순히 함수를 호출할 수 있을 뿐 함수에서 던지는 오류를 잡아내지는 못해요. 함수에서 던지는 오류를 잡아내려면 catch 구문을 사용해야 해요.

[이전](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/11.1.1.md)
[다음](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/11.1.3.md)

[처음으로](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/README.md)
